name: Python package
on:
    push:
        tags:
        - "v*.*.*"
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: release
    strategy:
        matrix:
          python-version:
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
        - uses: actions/checkout@v3
        - name: Build and publish to pypi
          uses: JRubics/poetry-publish@v2.0
          with:
            python_version: ${{ matrix.python-version }}
            pypi_token: ${{ secrets.PYPI_TOKEN }}
            poetry_install_options: "--sync --no-root"
            poetry_publish_options: "--dry-run --build"