name: Python package
on:
    push:
        tags:
        - "v*.*.*"
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: release
    strategy:
        matrix:
          python-version:          
          - '3.11'
    steps:
        - uses: actions/checkout@v3
        # - name: Build and publish to pypi
        #   uses: JRubics/poetry-publish@v2.0
        #   with:
        #     python_version: ${{ matrix.python-version }}
        #     pypi_token: ${{ secrets.PYPI_TOKEN }}
        #     poetry_install_options: "--sync --no-root"
        #     poetry_publish_options: "--dry-run --build"
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry

            poetry install            
        - name: Publish to PyPI
          run: |
            poetry publish --build
          env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}